community/custom_resources/python_custom_resource_helper/crhelper.py

missing logger in the timeout function caused an unhandled exception.

pass logger to timeout function

---

README.md

Need a space after your hash symbols so Markdown will make them into the right headings.

Added spaces for proper markdown formatting

---

aws/services/ECS/FargateLaunchType/clusters/private-vpc.yml
aws/services/ECS/FargateLaunchType/clusters/public-vpc.yml
aws/services/ECS/FargateLaunchType/services/private-subnet-private-service.yml
aws/services/ECS/FargateLaunchType/services/private-subnet-public-service.yml
aws/services/ECS/FargateLaunchType/services/public-service.yml

Was missing a `TaskExecutionRole` so the sample service templates only worked with public images from DockerHub. They now work out of the box for private images hosted in ECR as well.

Adding TaskExecutionRole to make it easier to pull images from ECR

---

community/custom_resources/python_custom_resource_helper/crhelper.py

timer continued in future invocations that ran on the same lambda container, explicitly cancelling to prevent that behavior.
Also removed the raise on line 141. When lambda raises an exception Cloudformation retries it's execution twice, resulting in unnecessary invocations.

explicitly cancel timer

---

aws/services/SQS/SQSStandardQueue.json

Based on the [CF Guide to SQS Queues](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html), I updated the description here to:
> The time in seconds that the delivery of all messages in the queue is delayed. You can specify an integer value of 0 to 900 (15 minutes).
I left out `The default value is 0.` since the template specifies a value of 5.
Happy to do whatever else is required to get this updated.

SQS DelaySeconds description seemed off

---

aws/services/ECS/FargateLaunchType/services/private-subnet-private-service.yml
aws/services/ECS/FargateLaunchType/services/private-subnet-public-service.yml
aws/services/ECS/FargateLaunchType/services/public-service.yml

Current templates hardcode port 80 in the Target Group for health checks rather than
using the ContainerPort parameter. This causes issues if using Docker images not using standard HTTP

Reference ContainerPort rather than hardcoding port 80 in Fargate ECS

---

aws/solutions/CloudFormationEndpointSignals/cfn-endpoint-creationpolicy-no-igw.yaml
aws/solutions/CloudFormationEndpointSignals/cfn-endpoint-creationpolicy.yaml
aws/solutions/CloudFormationEndpointSignals/cfn-endpoint-waitcondition-no-igw.yaml
aws/solutions/CloudFormationEndpointSignals/cfn-endpoint-waitcondition.yaml

* Removed unneeded permissions from instance profile role. 
* Removed unneeded keys from no-IGW instance templates.
* Modified templates to use AWS::Partition for defining the S3 endpoints.
* Added some "busy work" for the private instances to do before signaling.

Revisions to CloudFormation endpoint signal templates

---

aws/services/CloudFormation/MacrosExamples/PyPlate/python.yaml
aws/services/CloudFormation/MacrosExamples/StringFunctions/string.yaml

address various typos in macro examples

fix macro typos

---

aws/services/ECS/EC2LaunchType/clusters/private-vpc.yml
aws/services/ECS/EC2LaunchType/clusters/public-vpc.yml

This upgrades the default AMI used for an EC2 cluster orchestrated by ECS from Amazon Linux 1 to Amazon Linux 2

Upgrading the ECS EC2 clusters to Amazon Linux 2

---

aws/services/EC2/EC2InstanceWithSecurityGroupSample.yaml

Updated CF template to support t3 instance types. Updated HVM AMIs to use Amazon Linux 2. In addition, added three missing regions in europe and canada. I did not update any regions outside the standard commercial regions, nor did I update AMIs for HVMG2 or PV64.

updates to EC2 instance types, regions, and AMIs

---

aws/solutions/StackSetsResource/FunctionCode/crhelper.py
aws/solutions/StackSetsResource/FunctionCode/lambda_function.py

Hi Chuck,
I've applied a little lint/refactor in the 2 functions to make the code more pythonic.
Changes are:
- Renamed variables to lower case only (ex: `resourceId` to `resource_id`
- Replaced the string concatenation with `.format()` string method ([PEP3101](https://www.python.org/dev/peps/pep-3101/))
- Removed some extra parenthesys `()`
- Removed extra `#` in the header 
- Used 120 cols as the max line lenght (Yeah, blame me for not being completely [PEP8](https://www.python.org/dev/peps/pep-0008/), but nowadays 120 is the new normal :-) )
- Minor bugfixes

Stacksetresource lint

---

aws/services/SQS/SQSFIFOQueue.json

I updated comments of `SQSFIFOQueue.json`.
Supported regions of SQS FIFO Queue was updated on Nov 8.
- Amazon SQS FIFO Queues Now Available in Asia Pacific (Tokyo) and Asia Pacific (Sydney) Regions
- https://aws.amazon.com/about-aws/whats-new/2018/11/amazon-sqs-fifo-asia-pacific-tokyo-sydney/

Updated regions for SQSFIFOQueue.json

---

aws/services/S3/S3_Website_With_CloudFront_Distribution.yaml

Not sure why it's there, but when creating the CNAME record, this template adds 'https://' to the value, which causes the custom CNAME to not be resolved.

Remove http:// from dns resource record creation

---

aws/services/CloudFormation/MacrosExamples/Explode/.gitignore
aws/services/CloudFormation/MacrosExamples/Explode/README.md
aws/services/CloudFormation/MacrosExamples/Explode/lambda/explode.py
aws/services/CloudFormation/MacrosExamples/Explode/macro.yml
aws/services/CloudFormation/MacrosExamples/Explode/test.yml

This adds an example CFN Macro, "Explode", which uses values in a `Mapping` to generate multiple copies of a template Resource. It is similar to the Count Macro, except that you can provide different values to be used in each copy.

Add Explode macro

---

aws/solutions/PersistAZMapping/FindInMapAZs.json
aws/solutions/PersistAZMapping/FindInMapAZs.yaml

These sample templates deploy a VPC, with a pair of public and private subnets spread across two Availability Zones. They use a static AZ Mapping known as RegionMap to ensure that your resources persist in a given Availability Zone if we add or remove zones after you create your stack.

Persist AZs with Region Map in Mappings Section

---

aws/services/CloudFormation/MacrosExamples/Explode/README.md

Changing macro.yaml --> macro.yml
The file is called macro.yml and the documentation says macro.yaml

Fixing typo in MacrosExample Explode README.md

---

aws/services/CloudFormation/MacrosExamples/Count/src/index.py

Issue #, if available:
Current Lambda function in the Cloud Formation Count Macro does not support referencing the value of count as a parameter.
Description of changes:
Updated Lambda function for the Count macro in Cloud Formation templates to support the use of the Ref function to specify the value of count. This allows users to reference the value of count as a parameter in the template.

Ref support in Cloud Formation Count Macro

---

aws/services/IoT/lambda-iot-topicrule.yml
community/solutions/StaticWebSiteWithPipeline/stacks/functions.json

CloudFormation templates in aws-cloudformation-templates have been found to include a [deprecated Lambda function runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html) (nodejs8.10). The affected templates have been updated to a supported runtime (nodejs10.x).

Upgrade deprecated runtime nodejs8.10

---

aws/solutions/CloudFrontCustomOriginLambda@Edge/CloudFront.yaml

CloudFormation templates in aws-cloudformation-templates have been found to include a [deprecated Lambda function runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html) (nodejs6.10). The affected templates have been updated to a supported runtime (nodejs10.x).
Please note, **this pull request has been generated by a bot**; please check the base branch and files changed before merging.

Upgrade deprecated runtime nodejs6.10

---

community/services/Lambda/LambdaSample.yaml
community/services/Lambda/SAM/template.yml

CloudFormation templates in aws-cloudformation-templates have been found to include a [deprecated Lambda function runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html) (nodejs4.3). The affected templates have been updated to a supported runtime (nodejs10.x).
Please note, **this pull request has been generated by a bot**; please check the base branch and files changed before merging.

Upgrade deprecated runtime nodejs4.3

---

aws/solutions/lambda-backed-cloudformation-custom-resources/Fetch-AMI-From-Parameter-Store/lambda_function.py

Current Python script errors at the break and causes CloudFormation custom resource creation to hang. 
Removing the break so a failure response can be sent back to CloudFormation. Also removing json decode as image ID can be fetched from SSM param store and returned correctly without decoding.

Remove break and json decode

---

aws/solutions/AmazonCloudWatchAgent/inline/amazon_linux.template
aws/solutions/AmazonCloudWatchAgent/inline/centos.template
aws/solutions/AmazonCloudWatchAgent/inline/debian.template
aws/solutions/AmazonCloudWatchAgent/inline/redhat.template
aws/solutions/AmazonCloudWatchAgent/inline/suse.template
aws/solutions/AmazonCloudWatchAgent/inline/ubuntu.template
aws/solutions/AmazonCloudWatchAgent/inline/windows.template
aws/solutions/AmazonCloudWatchAgent/ssm/amazon_linux.template
aws/solutions/AmazonCloudWatchAgent/ssm/centos.template
aws/solutions/AmazonCloudWatchAgent/ssm/debian.template
aws/solutions/AmazonCloudWatchAgent/ssm/redhat.template
aws/solutions/AmazonCloudWatchAgent/ssm/suse.template
aws/solutions/AmazonCloudWatchAgent/ssm/ubuntu.template
aws/solutions/AmazonCloudWatchAgent/ssm/windows.template

Changed `CloudWagentAgent` to `CloudWatchAgent` in all `AmazonCloudWatchAgent` template descriptions.

Fix typo in 'CloudWatchAgent' template descriptions.

---

aws/services/CloudFormation/MacrosExamples/Explode/README.md
aws/services/CloudFormation/MacrosExamples/Explode/lambda/explode.py

Changes to the same Explode macro:
1. Fixed list recursion which couldn't walk a list within a list such as a Fn::Join.
2. Extended the Explode ability to be not just Resources but Conditions and Outputs as well.

Explode Macro: Fixed list recursion, Added ability to explode Conditions and Outputs

---

aws/services/S3/s3-bucket-and-policy-for-caa-delete-retention-v1.yaml
aws/services/S3/s3-bucket-and-policy-for-caa-secure-transport-v1.yaml
aws/services/S3/s3-bucket-and-policy-for-caa-sse-v1.yaml
aws/services/S3/s3-bucket-and-policy-for-caa-v1.yaml
aws/services/S3/s3-bucket-and-policy-for-caa-versioning-v1.yaml
aws/services/S3/s3-bucket-policy-for-caa-secure-transport-v1.yaml
aws/services/S3/s3-bucket-policy-for-caa-v1.yaml

Added multiple CloudFormation templates for variations in s3 cross account access buckets and policies.

Add CloudFormation templates for variations in s3 cross account access buckets and policies

---

aws/solutions/ADConnector/README.md
aws/solutions/ADConnector/src/adconnector_custom_resource.py
aws/solutions/ADConnector/src/package.sh
aws/solutions/ADConnector/src/requirements.txt
aws/solutions/ADConnector/templates/ADCONNECTOR.cfn.yaml

This solution creates an AD Connector to connect to an on-premises directory.
- (Optional) Create AWS resources (IAM role & instance profile) to support seamlessly join Windows EC2 instances to your AD Connector directory.
- (Optional) Create AWS resources (IAM role, instance profile, and secret) to support seamlessly join Linux EC2 instances to your AD Connector directory.
- (Optional) Creates a Domain Members Security Group with **EXAMPLE** rules allowing all Private IP communications inbound.

adconnector - Solution creates an AD Connector to connect to an on-premises directory.

---

aws/services/CloudFormation/MacrosExamples/StackMetrics/lambda/cfnresponse.py

One of the files was under the AWS Customer Agreement.
After obtaining internal OSPO approval, I've changed the source header to Apache-2.0. Please contact me internally if followup is needed related to the approval.

Relicensing cfnresponse.py to Apache-2.0

---

aws/services/CloudFormation/MacrosExamples/DatetimeNow/README.md
aws/services/CloudFormation/MacrosExamples/DatetimeNow/datetimenow.yaml
aws/services/CloudFormation/MacrosExamples/DatetimeNow/datetimenow_example.yaml

*Issue #, if available:* n/a
Added a new sample macro to retrieve the current Datetime as a formatted string. The format is exposed as a parameter so users can retrieve the format they prefer.

new sample macro DatetimeNow

---

.gitignore
aws/services/CloudFormation/MacrosExamples/DatetimeNow/README.md

*Issue #, if available:* n/a
Fix typos in readme for the DatetimeNow macro.
Also added .vscode folder to .gitignore.

fix typos in DatetimeNow macro readme

---

community/services/Lambda/LambdaSample.yaml

(similar to https://github.com/awslabs/aws-cloudformation-templates/commit/0b5c57536becd2e4301adcf426a878d0c8fbd375)
Noticed this file reporting
```
W2531 EOL runtime (nodejs10.x) specified. Runtime is EOL since 2021-05-31 and updating will be disabled at 2021-06-30. Please consider updating to nodejs14.x
Error: ./examples/template.yml:64:7
```
(https://github.com/ScottBrenner/cfn-lint-action/pull/61/checks?check_run_id=2708313079#step:4:6, fixed with https://github.com/ScottBrenner/cfn-lint-action/pull/62)
Proposing updating to the latest runtime per https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html (untested)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

fix: W2531 EOL runtime (nodejs10.x) specified

---

aws/services/CloudFormation/MacrosExamples/S3Objects/example.template
aws/services/CloudFormation/MacrosExamples/S3Objects/lambda/macro.py
aws/services/CloudFormation/MacrosExamples/S3Objects/lambda/resource.py

This PR adds support to specify a URL as a source for the S3Object macro. The macro will then download the file and upload to the specified target

Adding support for URL as a source

---

aws/services/CloudFormation/MacrosExamples/FindVPCResourceIds/README.md
aws/services/CloudFormation/MacrosExamples/FindVPCResourceIds/example.yaml
aws/services/CloudFormation/MacrosExamples/FindVPCResourceIds/macro.yaml

*Description of changes: Macro example added 'FindVPCResourceIDs'*
This CloudFormation Macro can be used to find following VPC ResourceId(s) by tags.
- VpcId
- SubnetIds
- SecurityGroupIds

Added Macro Example 'FindVPCResourceIds'

---

aws/services/Config/Config.yaml

- Fix syntax in lambda implementation
- Replace deprecated AWSConfigRole with AWS_ConfigRole
- See: https://docs.aws.amazon.com/config/latest/developerguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates

Fix aws config template

---

aws/services/AWSSupplyChain/SapPrivateLink/README.md
aws/services/AWSSupplyChain/SapPrivateLink/SapPrivateLink.yaml
aws/services/AWSSupplyChain/SapPrivateLink/SapPrivateLinkNoHostedZone.yaml

- Fix to always use 443 as targetGroup port that align with NLB listener
- Add support wildcard domain name
- Support concurrent duplicate stack creation and deletion
- Let customer specify protocol to connect to SAP from NLB to SAP (either HTTP or HTTPS) instead of always HTTP
- Enhance the README and input paramter decriptions to better guide customers

Some enhancements for AWSSupplyChain PrivateLink Setup

---

aws/services/ServiceCatalog/Product.yaml

Deploying using the default parameters was failing due to incorrect values. Updated the parameter default values to allow deployment to succeed without providing parameter values. Auto-formatted the document
This will resolve #351 

ServiceCatalog - Change default parameters

---

aws/solutions/AmazonCloudWatchAgent/inline/centos.template
aws/solutions/AmazonCloudWatchAgent/inline/debian.template
aws/solutions/AmazonCloudWatchAgent/inline/redhat.template
aws/solutions/AmazonCloudWatchAgent/inline/suse.template
aws/solutions/AmazonCloudWatchAgent/inline/ubuntu.template
aws/solutions/AmazonCloudWatchAgent/ssm/centos.template
aws/solutions/AmazonCloudWatchAgent/ssm/debian.template
aws/solutions/AmazonCloudWatchAgent/ssm/redhat.template
aws/solutions/AmazonCloudWatchAgent/ssm/suse.template
aws/solutions/AmazonCloudWatchAgent/ssm/ubuntu.template

Current version of templates for the CloudWatch Agent is outdated. Since easy_install is [deprecated ](https://setuptools.pypa.io/en/latest/history.html#v42-0-0), I have changed templates to use pip3 instead.

AmazonCloudWatchAgent: Easy Install is deprecated, changed to pip3 instead

---

aws/services/S3/S3_Website_With_CloudFront_Distribution.yaml

Issue #161
Issue #192 
Issue #315
This pull request resolves the issue which prevents the S3/CloudFront template from deploying successfully (#315). The change makes supplying a hosted zone optional (so users can leverage the default CloudFront URL), but also allows users to specify a ACM ARN if they would like to specify a hosted zone. This change is backwards compatible.
All references to the S3 bucket's domain were updated to reference the bucket's regional domain which resolves the issue with the incorrect endpoints listed in the map (#161). This change also removes the need to maintain the map.
This pull request also updates the origin configuration to use a CloudFront Origin Access Identity (OAI), and the ListBucket permission was added to properly propagate 403 errors (#192) (S3 …

Multiple fixes for S3/CloudFront template

---

aws/services/CloudFormation/MacrosExamples/StackMetrics/lambda/cfnresponse.py

Add a "reason" parameter to the send() function. This parameter is in the sample python module featured in the official documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html but is not present here.

Update cfnresponse.py to feature a reason parameter

---

aws/services/CloudFormation/MacrosExamples/Explode/macro.yml

The CloudFormation explode macro sample currently uses Python3.7 in the `macro.yml` template, which is deprecated. This change updates the Lambda to use 3.11.
*Testing:*
Testing the function locally, the macro lambda code appears to work at 3.11.
```text
bash-3.2$ .venv/bin/python --version
Python 3.11.4
bash-3.2$ .venv/bin/python -m pip list
Package    Version
---------- -------
pip        23.0.1
PyYAML     6.0.1
setuptools 67.6.1
[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: /Users/elliotsegler/workspace/aws-cloudformation-templates/aws/services/CloudFormation/MacrosExamples/Explode/.venv/bin/python -m pip install --upgrade pip
bash-3.2$ .venv/bin/python lambda/explode.py test.yml | …
```

Update Explode CFN Macro to Python 3.11

---

aws/services/CloudFormation/MacrosExamples/Boto3/README.md
aws/services/CloudFormation/MacrosExamples/Boto3/lambda/resource.py
aws/services/CloudFormation/MacrosExamples/Boto3/macro.template

#391
Refactor: update runtime python && edit README.md

ref: update python runtime && edit README.md

---

aws/services/CloudFormation/MacrosExamples/PyPlate/README.md
aws/services/CloudFormation/MacrosExamples/PyPlate/python.yaml

Added the ability for PyPlate to call AWS services via boto3.  When the PyPlate template is deployed an optional IAM Policy ARN can be provided which gets added to the Lambda execution role, providing AWS API permissions.  An optional override of the default Lambda 3-second timeout can also be provided; more time is needed for boto3 functionality, close on 5 seconds at least, so 10 seconds is recommended as a minimum.
Increased the Python version from 3.6 to 3.10.

Pyplate support for calling AWS APIs and Python version to 3.10.

---

aws/services/CloudFormation/MacrosExamples/DatetimeNow/README.md

as it currently refers to a non-existent transform and parameter.
1. change the transform name from `'String'` to `'DatetimeNow'`
When I run the example as is, I get the error `No transform named <account ID>::String found.`
1. change the parameter name from `'param'` to `'format'`
When I run the example as is, I get the error `Transform <account ID>::DatetimeNow failed with: 'format'`

Fix DatetimeNow macro example

---

aws/services/ECS/EC2LaunchType/clusters/public-vpc.yml

No issue for this.  I just noticed the instance types could use an update so I added them.
Added `t3` instance types to the EC2 ECS launch parameters.  The example looks like it predates these instance types and I was going to use them so I decided to contribute it back.

Updated example EC2 launch type template to include t3 instance types.

---

aws/services/CloudFormation/MacrosExamples/Explode/lambda/explode.py

*Issue #, if available:* None
Love this macro, although found it frustrating that there was no logging of errors anywhere. Examination of the code revealed that there was no real logging going on, and while I was looking at this found a bug in the exception handler within `replace_explode_in_string()`
Would be nice for CloudFormation to actually return a decent error message when there is an issue. Presume this can be done in the dict returned by the lambda handler.

Bug fix and improve logging to CloudWatch (Explode Macro)

---

aws/solutions/StackSetsResource/README.md

*Description of changes:* Since AWS CloudFormation released a built-in resource for StackSets, I updated the README file for the older StackSet resource to highlight that people should review the built-in resource before attempting to use the custom resource.

refer to newly released built-in StackSet resource

---

aws/services/CloudFormation/MacrosExamples/Explode/README.md

The provided file is test.yml, but the instructions reference test.yaml.
*Description of changes:* Made the README example consistent with the provided file names.

Fix reference to test.yml in Explode macro example

---

aws/solutions/CloudFrontCustomOriginLambda@Edge/CloudFront.yaml

Referred to the AWS documentation and provided a description.
China AWS documentation for some reason, still accurate:
https://docs.amazonaws.cn/en_us/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html
https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html

Paramater for compression had wrong description

---

aws/services/ECS/FargateLaunchType/clusters/private-vpc.yml
aws/services/ECS/FargateLaunchType/clusters/public-vpc.yml

Pass cfn-lint tests.
Changed IpProtocol to string type (lint error). Remove unneeded DependsOn since dependency is satisfied with the Ref (lint warning).

IpProtocol to string type, remove  DependsOn.

---

AppRunner/AppRunnerServiceFromECR.json
AppRunner/AppRunnerServiceFromECR.yaml

1. Ran cfn-lint and fixed the warning. DependsOn attribute on the  AppRunner resource is unnecessary, as the dependency is already being enforced through the use of Fn::GetAtt. 
2. Also the TCP port was hard-coded so made changes to pass in parameter
3. `bash ../scripts/test-all.sh                             
Formatting YAML files...
./AppRunnerServiceFromECR.yaml
Generating JSON files based on YAML...
Creating ./AppRunnerServiceFromECR.json based on ./AppRunnerServiceFromECR.yaml
Linting with config file ../scripts/../.cfnlintrc
Linting ./AppRunnerServiceFromECR.yaml
Guarding...
Running cfn-guard on ./AppRunnerServiceFromECR.yaml using ../scripts/rules.guard
Success
Success
Success
`
By submitting this pull request, I confirm that you …

Pass tcp port as parameter, fix W3005 Obsolete DependsOn per cfn-lint

---

RDS/RDS_MySQL_With_Read_Replica.yaml
RDS/RDS_PIOPS.yaml
RDS/RDS_with_DBParameterGroup.yaml

N/A
Added SecretsManager to RDS_MySQL_With_Read_Replica and RDS_PIOPS templates.
Updated MySQL Family version in RDS_with_DBParameterGroup template

Cleanup issues with sample RDS templates creating and deleting cleanly

---

CloudWatch/CloudWatch_Dashboard_NAT_FlowLogs.yaml

CFN template that creates CloudWatch Dashboard, adds 4 Logs Insights widgets that perform queries against VPC flow logs related to NAT Gateway traffic. 

CloudWatch Dashboard for NATGW VPC flow logs

---

EC2/EC2InstanceWithSecurityGroupSample.yaml

This PR addresses the same issue as identified in [PR #450], where using `groupName` (security group name) alongside the `subnet` parameter in the EC2 instance configuration results in an error. The CloudFormation YAML template has been updated to reference security groups by ID instead of name.
- Replaced `SecurityGroups` with `SecurityGroupIds` and used `!GetAtt` to fetch the security group ID.
- This update resolves the conflict between subnet and security group name when creating EC2 instances.
Similar to the changes made in PR #hoge, the AWS EC2 API does not allow the use of `groupName` (security group name) with a `subnet` parameter. Instead, security groups must be referenced by their ID, which is the focus of this fix.
The updated CloudFormation YAML template was successfully …

Fix: Replace SecurityGroups with SecurityGroupIds in YAML template

---

EC2/EC2InstanceWithSecurityGroupSample.json

This PR fixes an issue where specifying the security group name (`groupName`) in the `AWS::EC2::Instance` resource along with the subnet parameter causes an error. The security group should be referenced by its ID rather than by its name.
- Updated the `SecurityGroups` parameter to `SecurityGroupIds` and used `Fn::GetAtt` to retrieve the security group ID.
- This change ensures proper association between the subnet and security group, preventing errors during EC2 instance creation.
The AWS EC2 API does not allow the use of `groupName` (security group name) in combination with `subnet`. Instead, security groups must be referenced by their ID. This change addresses that limitation by updating the template to use the security group ID.
The updated template was successfully tested by creating …

Fix: Replace SecurityGroups with SecurityGroupIds in EC2 resource

---

DataFirehose/DataFirehoseDeliveryStream.yaml

Template to define an Amazon Firehose Delivery Stream with SSE and destination error logs enabled. Getting this setup was time consuming directly from the CloudFormation documentation, and there were not a lot of examples around. Hoping to  add some more examples to the internet with this template.
Created a new folder called `DataFirehose` for Firehose as none existed before. All tests pass from the bash script.

Amazon Firehose Delivery Stream

---

VPC/VPC_With_Managed_NAT_And_Private_Subnet.json
VPC/VPC_With_Managed_NAT_And_Private_Subnet.yaml

Issue #, if available:
N/A
Description of changes:
Remove duplicate aws::region in availabilityZone to avoid error: Value (us-east-1us-east-1a) for parameter availabilityZone is invalid.

Fix error value (us-east-1us-east-1a) for parameter availabilityZone is invalid

---

CloudWatch/CloudWatch_Dashboard_ClientVPN.yml

Creates a set of CloudWatch Logs Insights queries and a corresponding dashboard  for comprehensive AWS Client VPN usage reporting. It provides detailed insights into VPN usage patterns,   connection durations, data transfer volumes, and user activities across different authentication methods   (AD/SAML, Mutual Auth, and Mixed Auth)

CloudWatch Logs Insights queries and dashboard for comprehensive AWS Client VPN usage reporting

---

Solutions/AmazonCloudWatchAgent/inline/amazon_linux.json
Solutions/AmazonCloudWatchAgent/inline/amazon_linux.yaml
Solutions/AmazonCloudWatchAgent/inline/centos.json
Solutions/AmazonCloudWatchAgent/inline/centos.yaml
Solutions/AmazonCloudWatchAgent/inline/debian.json
Solutions/AmazonCloudWatchAgent/inline/debian.yaml
Solutions/AmazonCloudWatchAgent/inline/redhat.json
Solutions/AmazonCloudWatchAgent/inline/redhat.yaml
Solutions/AmazonCloudWatchAgent/inline/suse.json
Solutions/AmazonCloudWatchAgent/inline/suse.yaml
Solutions/AmazonCloudWatchAgent/inline/ubuntu.json
Solutions/AmazonCloudWatchAgent/inline/ubuntu.yaml
Solutions/AmazonCloudWatchAgent/inline/windows.json
Solutions/AmazonCloudWatchAgent/inline/windows.yaml
Solutions/AmazonCloudWatchAgent/ssm/amazon_linux.json
Solutions/AmazonCloudWatchAgent/ssm/amazon_linux.yaml
Solutions/AmazonCloudWatchAgent/ssm/centos.json
Solutions/AmazonCloudWatchAgent/ssm/centos.yaml
Solutions/AmazonCloudWatchAgent/ssm/debian.json
Solutions/AmazonCloudWatchAgent/ssm/debian.yaml
Solutions/AmazonCloudWatchAgent/ssm/redhat.json
Solutions/AmazonCloudWatchAgent/ssm/redhat.yaml
Solutions/AmazonCloudWatchAgent/ssm/suse.json
Solutions/AmazonCloudWatchAgent/ssm/suse.yaml
Solutions/AmazonCloudWatchAgent/ssm/ubuntu.json
Solutions/AmazonCloudWatchAgent/ssm/ubuntu.yaml
Solutions/AmazonCloudWatchAgent/ssm/windows.json
Solutions/AmazonCloudWatchAgent/ssm/windows.yaml

*Issue #, if available:* [Issue 397](https://github.com/aws-cloudformation/aws-cloudformation-templates/issues/397)
- **For Amazon LInux, Windows, Debian and Ubuntu** : Instead of hardcoded AMI IDs, updated the templates to use SSM parameter values for AMIs.
- **CentOs, SuSe and RedHat**: There are no SSM parameters available. Hence, added a mappings file to use latest available AMIs.

Updated templates with the SSM pseudo parameters for AMIs and mappings for other OS

---

EC2/InstanceWithCfnInit.yaml

add cfn-init codes
/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource Instance --region ${AWS::Region}
forget to init the cfn-init
add cfn-init codes
/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource Instance --region ${AWS::Region}

error in InstanceWithCfnInit.yaml -- forget to init the cfn-init

---

Solutions/CodeBuildAndCodePipeline/cloudformation-codebuild-template.json
Solutions/CodeBuildAndCodePipeline/cloudformation-codebuild-template.yaml
Solutions/CodeBuildAndCodePipeline/cloudformation-codepipeline-template.json
Solutions/CodeBuildAndCodePipeline/cloudformation-codepipeline-template.yaml
Solutions/CodeBuildAndCodePipeline/codebuild-app-build.yml
Solutions/CodeBuildAndCodePipeline/readme.md

*Issue #, if available:* [#459](https://github.com/aws-cloudformation/aws-cloudformation-templates/issues/459)
- Migrated CodePipeline trigger mechanism to use EventBridge events as per the official [documentation](https://docs.aws.amazon.com/codepipeline/latest/userguide/update-change-detection.html) recommendation.
- Updated codebuild image parameter to use latest 7.0 version
- Updated buildspec file to use dotnet:8.0 runtime
- Fixed yaml extensions in README file

Updated templates to use latest CodeBuild image, dotnet runtime and pipeline trigger mechanism

---

Solutions/CloudFrontCustomOriginLambda@Edge/CloudFront.json
Solutions/CloudFrontCustomOriginLambda@Edge/CloudFront.yaml
Solutions/CloudFrontCustomOriginLambda@Edge/README.md

*Issue #, if available:* [464](https://github.com/aws-cloudformation/aws-cloudformation-templates/issues/464)
- Replaced the ImportValue statements with Parameter values.
- Introduced parameters for networking resources like VpcId and Subnet Ids.
- Removed the custom resource that was used to create Lambda function version. CloudFormation supports the version resource now. We don't need a custom resource. 
- Other minor formatting changes.
- Updated ReadMe with the new parameters.

[Fix:464] Replaced imports with parameters and removed custom resource.

---

Solutions/OperatingSystems/RHEL9_cfn-hup.json
Solutions/OperatingSystems/RHEL9_cfn-hup.yaml
Solutions/OperatingSystems/Ubuntu22.04_cfn-hup.json
Solutions/OperatingSystems/Ubuntu22.04_cfn-hup.yaml
Solutions/OperatingSystems/ubuntu20.04_cfn-hup.json
Solutions/OperatingSystems/ubuntu20.04_cfn-hup.yaml

*Issue #, if available:* [Issue 470](https://github.com/aws-cloudformation/aws-cloudformation-templates/issues/470)
1. Updated SecurityGroup property to stack failures for all three templates.
2. Updated Ubuntu22.04 template to use SSM parameter instead of hardcoded values for AMI. RHEL and Ubuntu20 doesn't support SSM parameter, left them as is.

Updated SecurityGroupIds property and update ubuntu22 to use SSM parameter for AMI ID

---

AutoScaling/AutoScalingScheduledAction.yaml

fix launchConfig and !Join no `new line` problem
1. launchConfig deprecated problem
2. `insert new line` needed in !Join function. When using the `!Join` method, you need to explicitly include a newline character to indicate line breaks.
this PR resolve two problems
1. launchConfig has been deprecated, this PR replaces with LaunchTemplate
2. `inserting new line` is needed in !Join function, this PR replaces  with !Sub function

Update AutoScalingScheduledAction.yaml --- fix launchConfig deprecated problem and fix `insert new line` needed in !Join problem

---

ECS/EC2LaunchType/clusters/public-vpc.yaml

EC2 Auto Scaling no longer supports new EC2 features or new EC2 instance types released after December 31, 2022 through launch configurations. AWS recommended that you use launch templates to create new Auto Scaling groups and migrate any existing launch configurations to launch templates.
fix "launch configurations deprecated" problem with launch templates

Update public-vpc.yaml -- fix "launch configurations deprecated" problem

---

ECS/EC2LaunchType/clusters/private-vpc.yaml

EC2 Auto Scaling no longer supports new EC2 features or new EC2 instance types released after December 31, 2022 through launch configurations. AWS recommended that you use launch templates to create new Auto Scaling groups and migrate any existing launch configurations to launch templates.

Update private-vpc.yaml -- fix "launch configurations deprecated" problem
