aws/services/CloudFormation/FindInMap_Inside_Sub.yaml
Adds a CloudFormation template with examples of nesting functions inside Fn::Sub.
=> Add CloudFormation Fn::Sub examples

aws/solutions/VPCPeering/README.md
This PR is to update the wording and format on the README.md for the VPC Peering templates.
=> Wording update on the README.md

aws/solutions/HelperNonAmaznAmi/LICENSE, aws/solutions/HelperNonAmaznAmi/README.md, aws/solutions/HelperNonAmaznAmi/RHEL7_cfn-hup.template, aws/solutions/HelperNonAmaznAmi/article_wording, aws/solutions/HelperNonAmaznAmi/ubuntu16.04LTS_cfn-hup.template
Install helper scripts on non Amazon Linux and enable cfn-hup in Systemd
=> How to install helper scripts on non Amazon Linux

aws/services/DirectoryService/DirectoryServiceMicrosoftAD.json, aws/services/DirectoryService/DirectoryServiceSimpleAD.json, aws/services/EC2/SingleENIwithMultipleEIPs.json, aws/services/EMR/EMRCLusterGangliaWithSparkOrS3backedHbase.json, aws/services/EMR/EMRClusterWithAdditioanalSecurityGroups.json, aws/services/ElasticLoadBalancing/NetworkLoadBalancerWithEIPs.json, aws/services/SNS/SNSTopic.json, aws/services/SQS/SQSFIFOQueue.json, aws/services/SQS/SQSStandardQueue.json
added example stacks for (sqs , sns, emr, dir services)
=> added new services

aws/solutions/lambda-backed-cloudformation-custom-resources/get_latest_ami_id/LICENSE, aws/solutions/lambda-backed-cloudformation-custom-resources/get_latest_ami_id/NOTICE, aws/solutions/lambda-backed-cloudformation-custom-resources/get_latest_ami_id/README.md, aws/solutions/lambda-backed-cloudformation-custom-resources/get_latest_ami_id/deploy_get_latest_ami_id.yaml, aws/solutions/lambda-backed-cloudformation-custom-resources/get_latest_ami_id/example_usage_get_latest_ami_id.yaml, aws/solutions/lambda-backed-cloudformation-custom-resources/get_latest_ami_id/lambda_function.py, aws/solutions/lambda-backed-cloudformation-custom-resources/update_endpoint_policy/LICENSE, aws/solutions/lambda-backed-cloudformation-custom-resources/update_endpoint_policy/NOTICE, aws/solutions/lambda-backed-cloudformation-custom-resources/update_endpoint_policy/README.md, aws/solutions/lambda-backed-cloudformation-custom-resources/update_endpoint_policy/deploy_update_endpoint_policy.yaml, aws/solutions/lambda-backed-cloudformation-custom-resources/update_endpoint_policy/example_usage_update_endpoint_policy.yaml, aws/solutions/lambda-backed-cloudformation-custom-resources/update_endpoint_policy/lambda_function.py, aws/solutions/lambda-backed-cloudformation-custom-resources/update_kms_policy/LICENSE, aws/solutions/lambda-backed-cloudformation-custom-resources/update_kms_policy/NOTICE, aws/solutions/lambda-backed-cloudformation-custom-resources/update_kms_policy/README.md, aws/solutions/lambda-backed-cloudformation-custom-resources/update_kms_policy/deploy_update_kms_policy_lambda.yaml, aws/solutions/lambda-backed-cloudformation-custom-resources/update_kms_policy/example_usage_update_kms_policy.yaml, aws/solutions/lambda-backed-cloudformation-custom-resources/update_kms_policy/lambda_function.py
=> Add AWS Lambda backed CloudFormation custom resource examples

aws/services/CloudFormation/Elasticache-snapshot.template, aws/services/CloudFormation/HostnameChangeRHEL-Metadata.template, aws/services/CloudFormation/HostnameChangeRHEL-Userdata.template
Used for AWS Youtube video and general reference
=> Used for AWS Youtube video and general reference 

aws/solutions/Elasticache-snapshot.template, aws/solutions/HostnameChangeRHEL-Metadata.template, aws/solutions/HostnameChangeRHEL-Userdata.template
Moving some files to future proof and place in correct folder
=> Moving some files

aws/services/ECS/README.md
This PR corrects the "run on EC2" service links.
=> fix ec2 services links

aws/solutions/Fetch-AMI-From-Parameter-Store/Fetch-AMI-From-Parameter-Store.json, aws/solutions/Fetch-AMI-From-Parameter-Store/LICENSE.txt, aws/solutions/Fetch-AMI-From-Parameter-Store/README.md, aws/solutions/Fetch-AMI-From-Parameter-Store/lambda_function.py, aws/solutions/lambda-backed-cloudformation-custom-resources/Fetch-AMI-From-Parameter-Store/Fetch-AMI-From-Parameter-Store.json, aws/solutions/lambda-backed-cloudformation-custom-resources/Fetch-AMI-From-Parameter-Store/LICENSE.txt, aws/solutions/lambda-backed-cloudformation-custom-resources/Fetch-AMI-From-Parameter-Store/README.md, aws/solutions/lambda-backed-cloudformation-custom-resources/Fetch-AMI-From-Parameter-Store/lambda_function.py
A solution to automatically fetch public AMIs from the parameter store and launch instances using this AMI.
=> Fetch AMI ID from Parameter Store

aws/solutions/createVPCInterfaceEndpoint/README.md, aws/solutions/createVPCInterfaceEndpoint/lambda_vpce_interface.json
create VPC interface endpoint via lambda backed cloudFormation custom resource.
=> lambda backed cloudformation custom resource

community/custom_resources/python_custom_resource_helper/crhelper.py
Just something that stuck to my eye when browsing the code.
=> fix botolevel vs loglevel confusion

aws/solutions/StackSetsResource/FunctionCode/lambda_function.py, aws/solutions/StackSetsResource/README.md, aws/solutions/StackSetsResource/Templates/stackset-function-template.yaml
Enhanced Properties support for the Stack Set custom resource :
* Added support for AdministrationRoleARN and ExecutionRoleName properties.
* Made Parameters property optional.
Other enhancements:
* Added description for Lambda function so that the function has a description displayed by default in the AWS console.
* Added iam:PassRole permissions to Lambda function template.
=> Enhanced Properties of Stack Set custom resource

aws/services/CloudFormation/MacroExamples/PyPlate/README.md, aws/services/CloudFormation/MacroExamples/PyPlate/python.yaml, aws/services/CloudFormation/MacroExamples/PyPlate/python_example.yaml, aws/services/CloudFormation/MacroExamples/StringFunctions/README.md, aws/services/CloudFormation/MacroExamples/StringFunctions/string.yaml, aws/services/CloudFormation/MacroExamples/StringFunctions/string_example.yaml
=> add PyPlate and StringFunctions macro examples

aws/services/CloudFormation/MacrosExamples/PyPlate/README.md, aws/services/CloudFormation/MacrosExamples/StringFunctions/README.md
@LRomandine - also added link to github profile
=> cleanup author formatting in readme

aws/solutions/CloudFrontCustomOriginLambda@Edge/CloudFront.yaml, aws/solutions/CloudFrontCustomOriginLambda@Edge/README.md
Hi Team,
Please review commit and let me know if anything needs to be changed or modified.
Thanks,
Nikola Bravo
=> CloudFront and Lambda@Edge CloudFormation Template

aws/solutions/PrefixListResource/FunctionCode/crhelper.py, aws/solutions/PrefixListResource/FunctionCode/lambda_function.py, aws/solutions/PrefixListResource/LICENSE, aws/solutions/PrefixListResource/README.md, aws/solutions/PrefixListResource/Templates/cfn-endpoint-waitcondition.yaml, aws/solutions/PrefixListResource/Templates/function-template.yaml, aws/solutions/PrefixListResource/build.sh
Based on a regional service name, retrieve the prefix list ID for use in Security group egress rules.
=> Custom resource to get the prefix list associated a VPC Endpoint

aws/solutions/StackSetsResource/FunctionCode/lambda_function.py
StackSetsResource: catch throttling exception. Expand retries to take advantage of 15 minute Lambda timeout. Enhance error messages when exceptions occur to provide context as to which operation was underway.
=> CFN StackSetsResource: Catch throttling exception, expand retries to use new 15 min Lambda timeout

community/solutions/StaticS3CloudFront.yml
=> example of a static site setup with all dynamic references

aws/services/CloudFormation/MacrosExamples/Public-and-Private-Subnet-per-AZ/Create-Macro.yaml, aws/services/CloudFormation/MacrosExamples/Public-and-Private-Subnet-per-AZ/Create-Stack.yaml, aws/services/CloudFormation/MacrosExamples/Public-and-Private-Subnet-per-AZ/README.md
Updated Resource type in the macro template
=> Updated macro template

aws/services/ECS/README.md
Fixing template reference for Fargate launch type.
=> Fix template reference

community/solutions/StaticS3CloudFront.yml
Update `StaticS3CloudFront.yml` template to export the ARN of the S3 bucket hosting the website.
=> feat: export web bucket

aws/services/CloudFormation/MacrosExamples/Count/requirements.txt
Raised required version of requests to resolve security vulnerability.
=> Raised version of requirements to resolve security issue

community/codestar/custom-ci-cd-pipeline/README.md
UPDATED README.md:
- 'Steps' 5 and 6 deploy change sets to indicate the proper environment
- normalized step text instruction ordering
- added clarification text the *Important note* section regarding artifact.yml inclusion
=> UPDATED ./README.md verbiage for clarity

community/custom_resources/python_custom_resource_helper/README.md
crhelper has a new home, will leave the legacy code in place, just adding a notice to point to the new repo
=> update custom resource helper readme

aws/solutions/lambda-backed-cloudformation-custom-resources/get_vpc_main_route_table_id/LICENSE.txt, aws/solutions/lambda-backed-cloudformation-custom-resources/get_vpc_main_route_table_id/README.md, aws/solutions/lambda-backed-cloudformation-custom-resources/get_vpc_main_route_table_id/RouteTable.template, aws/solutions/lambda-backed-cloudformation-custom-resources/get_vpc_main_route_table_id/Routetable.py
=> Add solution to fetch VPC main route table id

aws/services/IoT/amzn2-greengrass-cfn.yml, aws/services/IoT/iotanalytics.yml, aws/services/IoT/lambda-iot-topicrule.yml
*Further details:*
https://aws.amazon.com/blogs/iot/automating-aws-iot-greengrass-setup-with-aws-cloudformation/ 
https://aws.amazon.com/blogs/iot/introducing-aws-cloudformation-support-for-aws-iot-analytics/
=> Add AWS IoT Greengrass and Analytics service examples

aws/services/CloudFormation/MacrosExamples/StringFunctions/string.yaml
Clean up of some undefined var references in the strings macro
=> fix undefined variable errors

aws/services/CloudFormation/MacrosExamples/Explode/lambda/explode.py
*Issue #207 *
[Bugfix] Explode fails if used with a resource whose property values are of type List
Updated Lambda function for the Explode macro in Cloud Formation templates to support its use in resources which have property values of type List.
The failure case is mentioned below
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: Explode
Mappings:
RoleMap:
Admin:
Type: AdministratorAccess
Alexa:
Type: AlexaForBusinessFullAccess
ApiGw:
Type: AmazonAPIGatewayAdministrator
Resources:
GenericRole:
ExplodeMap: RoleMap
Type: AWS::IAM::Role
Properties:
ManagedPolicyArns:
- "arn:aws:iam::aws:policy/!Explode Type"
AssumeRolePolicyDocument:
Version: 2012-10-17
Statement:
- Effect: Allow
Principal:
Service:
- cloudformation.amazonaws.com
Action:
- sts:AssumeRole
Path: …
```
=> Fixed Cloudformation Explode Macro to work with list items

aws/solutions/WordPress_Single_Instance.yaml
…default redirect, simplified the parameter groupings, and removed some extra whitespace.
*Issue #214 :*
This change ensures that the correct packages are used with the latest version of WordPress. This also fixes whitespaces and fixes the missing "yum update" which I consider a security limitation.
=> Updated the YUM packages, Added a default redirect

aws/services/NeptuneDB/Neptune.yaml
=> Fix spelling on description

aws/solutions/WordPress_Single_Instance.yaml
*Description of changes:* Updated Wordpress example
- Applied cfn-python-lint recommendations
- Removed use of PV instance types
=> Updated Wordpress example

aws/solutions/TaggingRootVolumesInEC2/Tagging_Root_volume.yaml
There was a region hardcoded into the UserData which has been updated.
Some of the bash scripts commands were not correct
=> Updating some hardcoded values and bug fixes

aws/services/CloudFormation/MacrosExamples/StackMetrics/lambda/cfnresponse.py
issue: #196 
replaces PR #258 
remove requests and call urllib3
=> swap requests to urllib3

aws/solutions/S3AccessLogs/README.md, aws/solutions/S3AccessLogs/templates/S3AccessLogs.cfn.yaml
This solution creates an S3 bucket to be used as a destination for S3 server access logs.
=> S3AccessLogs solution

aws/solutions/S3AccessLogs/README.md
updated encryption notes in README
=> encryption update

aws/services/CloudFormation/MacrosExamples/S3Objects/lambda/macro.py, aws/services/CloudFormation/MacrosExamples/S3Objects/lambda/resource.py, aws/services/CloudFormation/MacrosExamples/S3Objects/macro.template
*Issue #, if available:* #300
*Description of changes:* Updated S3Objects macro to use python3.8
=> Update s3 objects macro to python3

aws/solutions/ManagedAD/README.md, aws/solutions/ManagedAD/templates/MANAGEDAD.cfn.yaml
This solution creates an AWS Managed Microsoft AD directory that runs Active Directory (AD).
- (Optional) Create AWS resources (IAM role & instance profile) to support seamlessly join Windows EC2 instances to your AWS Managed Microsoft AD directory.
- (Optional) Create AWS resources (IAM role, instance profile, and secret) to support seamlessly join Linux EC2 instances to your AWS Managed Microsoft AD directory.
- (Optional) Creates a Domain Members Security Group with EXAMPLE rules allowing all Private IP communications inbound.
=> managedad - Solution that creates AWS Managed Microsoft AD directory that runs Active Directory (AD)

aws/solutions/VPCPeering/README.md, aws/solutions/VPCPeering/templates/VPCPeering-Accepter-Role.cfn.yaml, aws/solutions/VPCPeering/templates/VPCPeering-Accepter-Tag.cfn.yaml, aws/solutions/VPCPeering/templates/VPCPeering-Accepter.main.cfn.yaml, aws/solutions/VPCPeering/templates/VPCPeering-Requester.main.cfn.yaml, aws/solutions/VPCPeering/templates/VPCPeering-Updates.cfn.yaml
- Updated README and organized the details better.
- Added Tags to some resources
- Added option for specifying a KMS Key
=> updated readme, added tags, kms key option

aws/solutions/S3AccessLogs/README.md, aws/solutions/S3AccessLogs/templates/S3AccessLogs.cfn.yaml
- Updated README
- Updated Regex for S3 Bucket
=> updated readme, & regex

aws/solutions/VPCFlowLogs/README.md, aws/solutions/VPCFlowLogs/templates/VPCFlowLogs-main.cfn.yaml, aws/solutions/VPCFlowLogs/templates/VPCFlowLogsCloudWatch.cfn.yaml, aws/solutions/VPCFlowLogs/templates/VPCFlowLogsS3.cfn.yaml
- Updated README and organized the details better.
- Updated Regex Patterns
- Updated Assert Description
- Added Tags to some resources
=> updated readme, regex for s3, added some tags

aws/solutions/DirectoryServiceSettings/README.md, aws/solutions/DirectoryServiceSettings/src/directory_settings_custom_resource.py, aws/solutions/DirectoryServiceSettings/src/package.sh, aws/solutions/DirectoryServiceSettings/src/requirements.txt, aws/solutions/DirectoryServiceSettings/templates/DIRECTORY_SETTINGS.cfn.yaml
This solution updates the settings for an AD Connector or AWS Managed AD directory.
* Enables directory monitoring by using an Amazon SNS topic to send emails when the status of the directory changes.
* (Optional) Creates a custom access URL that can be used with AWS applications and services, to reach a login page that is associated to the directory.
* (Optional) Enable single sign-on, this allows users in your directory to access certain AWS services from a computer joined to the directory without having to enter their credentials separately. joined to the directory.
* (Optional) Creates **LAB EXAMPLE** IAM roles that can be used to delegate users/groups access to certain areas of the AWS Management Console.
* User/Group assignment to these IAM roles has to be …
=> directoryservicesettings - Solution updates the settings for an AD Connector or AWS Managed AD directory.

aws/solutions/DirectoryADClients/templates/DIRECTORY-AD-CLIENTS.yaml
=> updated regex

aws/solutions/ManagedAD/templates/MANAGEDAD.cfn.yaml
updated regex values, removed unneeded try/except
=> updated regex values, removed unneeded try/except

aws/solutions/ADConnector/src/adconnector_custom_resource.py, aws/solutions/ADConnector/src/package.sh, aws/solutions/ADConnector/templates/ADCONNECTOR.cfn.yaml
updated regex values, removed unneeded try/except, shell script enhancements
=> updated regex values, removed unneeded try/except, shell script enhancements

aws/solutions/LambaStaticIP/README.md, aws/solutions/LambaStaticIP/lambda-static.cfn.yaml
New Service that demonstrates a static Egress IP address for Lambda in a high available architecture
=> New Lambda Static IP Service

aws/services/AppRunner/AppRunnerServiceFromECR.yml
No Open Issue available.
Added a template for new AWS App Runner Service creation from existing ECR Repository. 
=> Add App Runner Template

aws/services/Config/Config.yaml
I updated the version of the runtime so that it is accepted by a current AWS deployment. 
=> Update version of runtime to nodejs14.x for the AWS Config CFN example

aws/services/CloudFormation/MacrosExamples/StringFunctions/string.yaml
=> changing the python version to 3.7

aws/services/CloudFormation/MacrosExamples/Public-and-Private-Subnet-per-AZ/Create-Macro.yaml
*Issue #366,
Modified python version from 3.6 to 3.9 
=> changing the python version to 3.9 for Public-and-Private-Subnet-per-AZ

aws/services/AWSSupplyChain/SapPrivateLink/README.md, aws/services/AWSSupplyChain/SapPrivateLink/SapPrivateLink.yaml, aws/services/AWSSupplyChain/SapPrivateLink/SapPrivateLinkNoHostedZone.yaml
…structure for AWS Supply Chain SAP customers
=> Add CloudFormation templates to help customer setup privateLink infra

aws/services/AWSSupplyChain/SapPrivateLink/SapPrivateLink.yaml, aws/services/AWSSupplyChain/SapPrivateLink/SapPrivateLinkNoHostedZone.yaml
=> Change descriptions of AwsSupplyChain's privateLink setup templates

aws/solutions/CodeBuildAndCodePipeline/cloudformation-codebuild-template.yml, aws/solutions/CodeBuildAndCodePipeline/cloudformation-codepipeline-template.yml, aws/solutions/CodeBuildAndCodePipeline/codebuild-app-build.yml, aws/solutions/CodeBuildAndCodePipeline/codebuild-app-deploy.yml, aws/solutions/CodeBuildAndCodePipeline/readme.md
Adding a cloud formation template for creating a CodeCommit repository and CodeBuild jobs
Adding a cloud formation template for creating a CodePipeline that uses the CodeBuild jobs and is triggered on changes to the repository
=> Adding CodeBuildAndCodePipeline

aws/services/CloudFormation/MacrosExamples/StackMetrics/lambda/cfnresponse.py
The cfnresponse code is out of date from what the documentation indicates is the current code. This PR updates the code to match the source code described in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html#cfn-lambda-function-code-cfnresponsemodule-source
=> Update cfnresponse code to match documentation

.gitignore, README.md, scripts/rules.guard, scripts/test-all.sh, scripts/test-single.sh
Guard rules are based on CIS top 20. The linter and guard checks are not passing currently.
=> Addings scripts for validation and readme changes

aws/services/EC2/EC2InstanceWithSecurityGroupSample.yaml
I am fairly certain this is not an allowed value for InstanceType
=> Remove r3.12xlarge

aws/services/CloudFormation/MacrosExamples/Explode/README.md
This just cost me so much time :-(
The documentation for this is wrong. It does not wirk without the parenthesis.
=> Correct README.md

aws/services/SQS/SQSStandardQueue.json
*Issue #242 , 
*Description of changes: Adding KmsMasterKeyId as Optional parameter. If empty - don't set encryption to SQS*
=> Adding KMS encryption option to SQS

community/services/apigateway/README.md, community/services/apigateway/apigateway_lambda_integration.json
#204 
Added new API Gateway service 
=> Api gateway request

aws/solutions/HelperNonAmaznAmi/README.md
=> markdown fixes

.cfnlintrc, community/services/EC2/ec2_with_waitcondition_template.json, community/services/Lambda/LambdaSample.yaml, community/services/VPC/vpc_template.json, community/services/apigateway/apigateway_lambda_integration.json, community/solutions/StaticWebSiteWithPipeline/stacks/distribution.json, community/solutions/StaticWebSiteWithPipeline/stacks/pipeline.json, community/solutions/StaticWebSiteWithPipeline/stacks/s3buckets.json
- Clean up a majority of community cfn-lint issues
=> Clean up a majority of community cfn-lint issues

community/services/Lambda/LambdaSample.yaml, scripts/create-json-all.sh, scripts/create-json-single.sh, scripts/format-yaml-all.sh, scripts/format-yaml-single.sh
- Fix scripts calling bash and format community yml files
=> Fix scripts calling bash and format community yml files

Lambda/LambdaSample.json, Lambda/LambdaSample.yaml
N/A
1. Return a response
2. bash ../scripts/test-all.sh                                            
Formatting YAML files...
./LambdaSample.yaml
Generating JSON files based on YAML...
Creating ./LambdaSample.json based on ./LambdaSample.yaml
Linting with config file ../scripts/../.cfnlintrc
Linting ./LambdaSample.yaml
Guarding...
Running cfn-guard on ./LambdaSample.yaml using ../scripts/rules.guard
=> Return a non empty response per Amazon Q recommendation

Solutions/ADConnector/templates/ADCONNECTOR.cfn.yaml, Solutions/ManagedAD/templates/MANAGEDAD.cfn.yaml
=> Resolve some sub arn issues

README.md
*Issue #, if available:* 
Guess this was missed in a copy/paste over. The upstream that contributor would want to use is this repo compared to the rain repo.
=> Docs(readme): Fix upstream

CloudFormation/MacrosExamples/StringFunctions/README.md
remove hyphen, which made the example invalid
=> error in README.md

NeptuneDB/Neptune.json, NeptuneDB/Neptune.yaml, ServiceCatalog/Product.json, ServiceCatalog/Product.yaml, ServiceCatalog/README.md
*Issue #, if available:* 
1. [Issue#466](https://github.com/aws-cloudformation/aws-cloudformation-templates/issues/466)
2. [Issue#442](https://github.com/aws-cloudformation/aws-cloudformation-templates/issues/442)
1. Updated import name in the product.yaml file to fix the stack provisioning error.
2. Updated the logs:DescribeLogStreams permission in NeptuneDB template.
=> Fixed the import name in product.yaml and correct permission in Neptune template

DMS/DMSAuroraToS3FullLoadAndOngoingReplication.json, DMS/DMSAuroraToS3FullLoadAndOngoingReplication.yaml, DMS/README.md
*Issue #, if available:* [472](https://github.com/aws-cloudformation/aws-cloudformation-templates/issues/472)
- Parameterized password for database
- Removed the SubnetParametergroup resource so that the default parameter group will be used. 
=> Updated DMS template to resolve stack failures

EFS/EFSAccessPoint.yaml
*Description of changes:* Added CloudFormation script to creates an simple EFS file system along with an access point. Passes all test and has been linted.
=> Added EFSAccessPoint

EMR/EMRClusterWithAdditionalSecurityGroups.json, EMR/EMRClusterWithAdditionalSecurityGroups.yaml, ElasticLoadBalancing/ELBGuidedAutoScalingRollingUpgrade.json, ElasticLoadBalancing/ELBGuidedAutoScalingRollingUpgrade.yaml, ElasticLoadBalancing/ELBStickinessSample.json, ElasticLoadBalancing/ELBStickinessSample.yaml, ElasticLoadBalancing/ELBWithLockedDownAutoScaledInstances.json, ElasticLoadBalancing/ELBWithLockedDownAutoScaledInstances.yaml, ElasticLoadBalancing/ELB_Access_Logs_And_Connection_Draining.json, ElasticLoadBalancing/ELB_Access_Logs_And_Connection_Draining.yaml
*Issue #, if available:* https://github.com/aws-cloudformation/aws-cloudformation-templates/issues/478
- Parameterized Security Groups in EMR template. 
- Update UserData for ELB templates to resolve execution errors. 
- Used SSM parameter for AMI Id instead of hardcoded values.
=> Updated EMR and ELB templates
